#!/usr/bin/env python3

import getopt
import sys
import random
import string

def main(argv):

    lca = string.ascii_lowercase
    uca = string.ascii_uppercase
    num = string.digits
    ext = string.punctuation

    leng = 8
    sets = lca + uca + num + ext
    opts, args = getopt.getopt(argv, "hl:", ["length="])

    for opt, arg in opts:
        if opt == "-h":
            print('pswd-gen -l <password length>')
            sys.exit()
        elif opt in ("-l", "--length"):
            leng = int(arg)
    p =  "".join(random.sample(sets,leng))
    print(p)

if __name__ == "__main__":
    main(sys.argv[1:])
