#!/usr/bin/env python3

import getopt
import sys

def print_default():
	for style in range(8):
		for fg in range(30,38):
			s1 = ''
			for bg in range(40,48):
				format = ';'.join([str(style), str(fg), str(bg)])
				s1 += '\x1b[%sm %s \x1b[0m' % (format, format)
			print(s1)
		print('\n')

def print_colorticket():
	print("""
 \x1b[30m████\x1b[1m▄\x1b[0m  \x1b[31m████\x1b[1m▄\x1b[0m  \x1b[32m████\x1b[1m▄\x1b[0m  \x1b[33m████\x1b[1m▄\x1b[0m  \x1b[34m████\x1b[1m▄\x1b[0m  \x1b[35m████\x1b[1m▄\x1b[0m  \x1b[36m████\x1b[1m▄\x1b[0m  \x1b[37m████\x1b[1m▄\x1b[0m  
 \x1b[30m████\x1b[1m█\x1b[0m  \x1b[31m████\x1b[1m█\x1b[0m  \x1b[32m████\x1b[1m█\x1b[0m  \x1b[33m████\x1b[1m█\x1b[0m  \x1b[34m████\x1b[1m█\x1b[0m  \x1b[35m████\x1b[1m█\x1b[0m  \x1b[36m████\x1b[1m█\x1b[0m  \x1b[37m████\x1b[1m█\x1b[0m  
 \x1b[30m████\x1b[1m█\x1b[0m  \x1b[31m████\x1b[1m█\x1b[0m  \x1b[32m████\x1b[1m█\x1b[0m  \x1b[33m████\x1b[1m█\x1b[0m  \x1b[34m████\x1b[1m█\x1b[0m  \x1b[35m████\x1b[1m█\x1b[0m  \x1b[36m████\x1b[1m█\x1b[0m  \x1b[37m████\x1b[1m█\x1b[0m  
 \x1b[1m\x1b[30m ▀▀▀▀  \x1b[1m\x1b[31m ▀▀▀▀   \x1b[32m▀▀▀▀   \x1b[33m▀▀▀▀   \x1b[34m▀▀▀▀   \x1b[35m▀▀▀▀   \x1b[36m▀▀▀▀   \x1b[37m▀▀▀▀\x1b[0m  
""")

def print_ghosts():
	print("""
\x1b[31m    ▄▄▄      \x1b[32m    ▄▄▄      \x1b[33m    ▄▄▄      \x1b[34m    ▄▄▄      \x1b[35m    ▄▄▄      \x1b[36m    ▄▄▄     
\x1b[31m   ▀█▀██  ▄  \x1b[32m   ▀█▀██  ▄  \x1b[33m   ▀█▀██  ▄  \x1b[34m   ▀█▀██  ▄  \x1b[35m   ▀█▀██  ▄  \x1b[36m   ▀█▀██  ▄ 
\x1b[31m ▀▄██████▀   \x1b[32m ▀▄██████▀   \x1b[33m ▀▄██████▀   \x1b[34m ▀▄██████▀   \x1b[35m ▀▄██████▀   \x1b[36m ▀▄██████▀  
\x1b[31m    ▀█████   \x1b[32m    ▀█████   \x1b[33m    ▀█████   \x1b[34m    ▀█████   \x1b[35m    ▀█████   \x1b[36m    ▀█████  
\x1b[31m       ▀▀▀▀▄ \x1b[32m       ▀▀▀▀▄ \x1b[33m       ▀▀▀▀▄ \x1b[34m       ▀▀▀▀▄ \x1b[35m       ▀▀▀▀▄ \x1b[36m       ▀▀▀▀▄
\x1b[1m
  \x1b[31m    ▄▄▄      \x1b[32m    ▄▄▄      \x1b[33m    ▄▄▄      \x1b[34m    ▄▄▄      \x1b[35m    ▄▄▄      \x1b[36m    ▄▄▄     
  \x1b[31m   ▀█▀██  ▄  \x1b[32m   ▀█▀██  ▄  \x1b[33m   ▀█▀██  ▄  \x1b[34m   ▀█▀██  ▄  \x1b[35m   ▀█▀██  ▄  \x1b[36m   ▀█▀██  ▄ 
  \x1b[31m ▀▄██████▀   \x1b[32m ▀▄██████▀   \x1b[33m ▀▄██████▀   \x1b[34m ▀▄██████▀   \x1b[35m ▀▄██████▀   \x1b[36m ▀▄██████▀  
  \x1b[31m    ▀█████   \x1b[32m    ▀█████   \x1b[33m    ▀█████   \x1b[34m    ▀█████   \x1b[35m    ▀█████   \x1b[36m    ▀█████  
  \x1b[31m       ▀▀▀▀▄ \x1b[32m       ▀▀▀▀▄ \x1b[33m       ▀▀▀▀▄ \x1b[34m       ▀▀▀▀▄ \x1b[35m       ▀▀▀▀▄ \x1b[36m       ▀▀▀▀▄
\x1b[0m
""")

def print_space_invader():
	print("""
 \x1b[31m  ▀▄   ▄▀     \x1b[32m ▄▄▄████▄▄▄    \x1b[33m  ▄██▄     \x1b[34m  ▀▄   ▄▀     \x1b[35m ▄▄▄████▄▄▄    \x1b[36m  ▄██▄  
 \x1b[31m ▄█▀███▀█▄    \x1b[32m███▀▀██▀▀███   \x1b[33m▄█▀██▀█▄   \x1b[34m ▄█▀███▀█▄    \x1b[35m███▀▀██▀▀███   \x1b[36m▄█▀██▀█▄
 \x1b[31m█▀███████▀█   \x1b[32m▀▀███▀▀███▀▀   \x1b[33m▀█▀██▀█▀   \x1b[34m█▀███████▀█   \x1b[35m▀▀███▀▀███▀▀   \x1b[36m▀█▀██▀█▀
 \x1b[31m▀ ▀▄▄ ▄▄▀ ▀   \x1b[32m ▀█▄ ▀▀ ▄█▀    \x1b[33m▀▄    ▄▀   \x1b[34m▀ ▀▄▄ ▄▄▀ ▀   \x1b[35m ▀█▄ ▀▀ ▄█▀    \x1b[36m▀▄    ▄▀
\x1b[1m
   \x1b[31m▄ ▀▄   ▄▀ ▄   \x1b[32m ▄▄▄████▄▄▄    \x1b[33m  ▄██▄     \x1b[34m▄ ▀▄   ▄▀ ▄   \x1b[35m ▄▄▄████▄▄▄    \x1b[36m  ▄██▄  
   \x1b[31m█▄█▀███▀█▄█   \x1b[32m███▀▀██▀▀███   \x1b[33m▄█▀██▀█▄   \x1b[34m█▄█▀███▀█▄█   \x1b[35m███▀▀██▀▀███   \x1b[36m▄█▀██▀█▄
   \x1b[31m▀█████████▀   \x1b[32m▀▀▀██▀▀██▀▀▀   \x1b[33m▀▀█▀▀█▀▀   \x1b[34m▀█████████▀   \x1b[35m▀▀▀██▀▀██▀▀▀   \x1b[36m▀▀█▀▀█▀▀
   \x1b[31m ▄▀     ▀▄    \x1b[32m▄▄▀▀ ▀▀ ▀▀▄▄   \x1b[33m▄▀▄▀▀▄▀▄   \x1b[34m ▄▀     ▀▄    \x1b[35m▄▄▀▀ ▀▀ ▀▀▄▄   \x1b[36m▄▀▄▀▀▄▀▄
\x1b[0m

                                     \x1b[37m▌\x1b[0m

                                   \x1b[37m▌\x1b[0m

                              \x1b[37m    ▄█▄    \x1b[0m
                              \x1b[37m▄█████████▄\x1b[0m
                              \x1b[37m▀▀▀▀▀▀▀▀▀▀▀\x1b[0m
""")


def main(argv):
	opts, args = getopt.getopt(argv, "ht:", ["type="])

	for opt, arg in opts:
		if opt == "-h":
			print("colortest [-t <type>]\n\nType:\n- s: Space Invader\n- g: Ghosts\n- c: Colorcards")
			sys.exit()
		elif opt in ("-t", "--type"):
			t=arg
			if t == "s":
				print_space_invader()
				sys.exit()
			elif t == "g":
				print_ghosts()
				sys.exit()
			elif t == "c":
				print_colorticket()
				sys.exit()
			else:
				print("\x1b[0;30;40mInvalid input. reset to defualt.")
				print_default()
				sys.exit()
	print_default()

if __name__ == "__main__":
	main(sys.argv[1:])

