#!/usr/bin/env python3

import os
import sys

def i_s(name):
    if name == "pascal":

        os.system("apt install -y fp-compiler fp-ide")
    elif name == "nvm":
        os.system()
    elif name == "gvm":
        os.system()


def main():
    args = sys.argv[1:]
    for arg in sys.argv:
        if arg == "install":
            i_s(args[1])

if __name__ == "__main__":
    main()
